@startuml

class Link<V> {
  +V value
  +Link<V> next
  +V value()
  +Link<V> next()
}

class HashMap<V> {
  +Entry<V>[] valueStore
  +void put(String key, V value)
  +Optional<V> get(String key)
  +String toString()
  +boolean equals(HashMap)
}

class Entry<V> {
  +String key
  +String key()
}

class LinkedStack<V> {
  +Link<V> first
  +int size
  +void add(V value)
  +Optional<V> pop()
  +Optional<V> peek()
  +int size()
  +boolean isEmpty()
  +boolean equals(LinkedStack<V>)
}

class Node {
  +String name
  +Node parent
  +LinkedStack<Node> children
  +String name()
  +Node parent()
  +LinkedStack<Node> children()
  +void addChild()
  +boolean equals(Node)
}

class ProductsParser {
  +int indent
  +Node[] parse(String directory)
}

class CostsParser {
  +HashMap<Integer> parse(String file)
}

class ProductCalculator {
  +int calculateProduct(Node product)
}

class Application {
  +void calculateProductCosts()
}

HashMap *-- Entry
LinkedStack *-- Link
Link <|-left- Entry

ProductsParser *-- Node
CostsParser *-- HashMap
ProductCalculator *-- LinkedStack
LinkedStack -right-* Node

Application *-- ProductsParser
Application *-- ProductCalculator
Application *-- CostsParser
Application *-- HashMap

hide circle

@enduml
